apiVersion: v1
kind: Service
metadata:
    name: leaderboard
spec:
    ports:
    - port: 8080 
    selector:
        app: leaderboard
---
apiVersion: v1
kind: Service
metadata:
    name: web
spec:
    ports:
    - port: 8080 
    selector:
        app: web
